### ISSUE TITLE
UE5 support

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE#105]
A new branch (or repository if major changes in architecture, TBD) should start to implement UE5 Support

**Comment by ddthejj** [comment]
Added a new branch that incorporates UE5 EA 2 in 5f0f6ec7bb636f343ba0b97817b1774ea3baa76c - The main branch of UE5 is still in development and no official release has been done, so there is currently no target for release. It's better to wait for them to release to incorporate UE5 main support.

**Comment by jetXS** [comment]
On hold until preview release of UE5

**Comment by jetXS** [comment]
UE5 (5.0.2) support is ongoing in branch 5.0.
