### ISSUE TITLE
Support for Ndisplay and cluster rendering

### ISSUE THREAD

**Issue by jetXS** [TouchDesigner/TouchEngine-UE#113]
To be checked out before getting started

Ndisplay: https://docs.unrealengine.com/4.27/en-US/WorkingWithMedia/IntegratingMedia/nDisplay/Overview/
Cluster events: https://docs.unrealengine.com/4.27/en-US/WorkingWithMedia/IntegratingMedia/nDisplay/ClusterEvents/

**Comment by jetXS** [comment]
Tracking in internal tools. Planned for 2023.

**Comment by oliver-ellmers-dimension** [comment]
Hello - I was wondering what the status of nDisplay Cluster rendering currently is with the latest TouchEngine?

More specifically in UE from my understanding when using both the Inner and Outer frustrum, UE spins up two separate rendering processes for Outer/Inner. Will the Texture OUT from a TouchEngine Component TOX display in both frustrum's?

**Comment by jetXS** [comment]
Hello Oliver,

We went through some testing of nDisplay and had some preliminary feedback stating that the basic features are working. We have a few improvements coming in a future release focused around process sync, which we believe should help, as well as some additional tweaks around cluster events.

The specific setup you describe wasn't fully tested and we invite users with such cases to contact us via support.

Best,
Michel
