### ISSUE TITLE
doesn't work as windows build

### ISSUE THREAD

**Issue by miwa-maroon** [TouchDesigner/TouchEngine-UE#117]
I'm not sure where I can ask question and here is correct. But I have the problem that TouchEngine process doesn't work when I launch as windows build. If I do as play in editor, it works.
To do test at another environment, I tried it in TouchEngine UE4 plugin sample, it worked as windows build and play in editor.
Is it the problem of my wrong building project or bug??

**Comment by jetXS** [comment]
Hey @miwa-maroon - apologies for the delay.

Can you give that another try with the latest release to see if some changes solved your issue ?

Note that there is also a new UE5.0.2 branch for the Plugin if you work in UE5 - but you'll have to compile everything manually.

Best,
Michel

**Comment by jetXS** [comment]
Stale issue, closing.
